/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#1e100c",
        "surface-dim": "#1e100c",
        "surface-bright": "#483530",
        "surface-container-lowest": "#180b07",
        "surface-container-low": "#271813",
        "surface-container": "#2c1c17",
        "surface-container-high": "#372621",
        "surface-container-highest": "#43302b",
        "on-surface": "#fadcd4",
        "on-surface-variant": "#e4beb4",
        "inverse-surface": "#fadcd4",
        "inverse-on-surface": "#3e2c27",
        "outline": "#ab8980",
        "outline-variant": "#5b4039",
        "surface-tint": "#ffb5a0",
        "primary": "#ffb5a0",
        "on-primary": "#5f1500",
        "primary-container": "#ff5722",
        "on-primary-container": "#541200",
        "inverse-primary": "#b02f00",
        "secondary": "#b7c8e1",
        "on-secondary": "#213145",
        "secondary-container": "#3a4a5f",
        "on-secondary-container": "#a9bad3",
        "tertiary": "#86cfff",
        "on-tertiary": "#00344c",
        "tertiary-container": "#019ad8",
        "on-tertiary-container": "#002d43",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbd1",
        "primary-fixed-dim": "#ffb5a0",
        "on-primary-fixed": "#3b0900",
        "on-primary-fixed-variant": "#862200",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-fixed": "#c8e6ff",
        "tertiary-fixed-dim": "#86cfff",
        "on-tertiary-fixed": "#001e2e",
        "on-tertiary-fixed-variant": "#004c6d",
        "background": "#1e100c",
        "on-background": "#fadcd4",
        "surface-variant": "#43302b"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "mobile-headline": ["Inter"],
        "data-tabular": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "display-telemetry": ["JetBrains Mono"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "mobile-headline": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "data-tabular": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-telemetry": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      },
      spacing: {
        "unit": "4px",
        "gutter": "8px",
        "margin-panel": "12px",
        "container-padding": "16px"
      },
    },
  },
  plugins: [],
}
